sonarr_url: 'http://localhost:8989'
sonarr_api_key: 'YOUR_SONARR_API_KEY'
tmdb_api_key: 'YOUR_TMDB_API_KEY'

skip_unmonitored: true
utc_offset: +0

################################################################################
##########                        NEW SEASON:                         ##########
################################################################################

future_days_new_season: 31

collection_new_season:
  collection_name: "New Season Soon"
  smart_label: title.desc
  sort_title: "+1_2New Season Soon"
  ignore_blank_results: true

backdrop_new_season:
  enable: true
  back_color: "#228B22"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text_new_season:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "NEW SEASON"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"

################################################################################
##########                     UPCOMING EPISODE:                      ##########
################################################################################

future_days_upcoming_episode: 31

collection_upcoming_episode:
  collection_name: "Upcoming Episode"
  smart_label: title.desc
  sort_title: "+1_2Upcoming Episode"
  ignore_blank_results: true
  
backdrop_upcoming_episode:
  enable: true
  back_color: "#006580"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text_upcoming_episode:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "NEXT EPISODE"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"
  
################################################################################
##########                      UPCOMING FINALE:                      ##########
################################################################################

future_days_upcoming_finale: 31

collection_upcoming_finale:
  collection_name: "Upcoming Finale"
  smart_label: title.desc
  sort_title: "+1_2Upcoming Finale"
  ignore_blank_results: true
  
backdrop_upcoming_finale:
  enable: true
  back_color: "#9932CC"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text_upcoming_finale:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "FINALE AIRS"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"

################################################################################
##########                           ENDED:                           ##########
################################################################################

collection_ended:
  collection_name: "Ended Shows"
  smart_label: title.desc
  sort_title: "+1_2Ended Shows"
  ignore_blank_results: true

backdrop_ended:
  enable: false
  back_color: "#000000"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text_ended:
  use_text: "E N D E D"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 50
  font_size: 70
  font_color: "#00ff3d"

################################################################################
##########                        CANCELLED:                        ##########
################################################################################

collection_cancelled:
  collection_name: "Cancelled Shows"
  smart_label: title.desc
  sort_title: "+1_2Cancelled Shows"
  ignore_blank_results: true

backdrop_cancelled:
  enable: false
  back_color: "#000000"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text_cancelled:
  use_text: "C A N C E L L E D"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 50
  font_size: 70
  font_color: "#ff0000"

################################################################################
##########                         RETURNING:                         ##########
################################################################################

collection_returning:
  collection_name: "Returning Shows"
  smart_label: title.desc
  sort_title: "+1_2Returning Shows"
  ignore_blank_results: true

backdrop_returning:
  enable: false
  back_color: "#000000"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text_returning:
  use_text: "R E T U R N I N G"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 50
  font_size: 70
  font_color: "#ff9000"

################################################################################
##########                       SEASON FINALE:                       ##########
################################################################################

recent_days_season_finale: 7

collection_season_finale:
  collection_name: "Season Finale"
  smart_label: title.desc
  sort_title: "+1_2Season Finale"
  ignore_blank_results: true

backdrop_season_finale:
  enable: true
  back_color: "#ffb902"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text_season_finale:
  use_text: "SEASON FINALE"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#000000"

################################################################################
##########                       FINAL EPISODE:                       ##########
################################################################################

recent_days_final_episode: 21

collection_final_episode:
  collection_name: "Final Episode"
  smart_label: title.desc
  sort_title: "+1_2Final Episode"
  ignore_blank_results: true

backdrop_final_episode:
  enable: true
  back_color: "#ffb902"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text_final_episode:
  use_text: "FINAL EPISODE"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#000000"